### ISSUE TITLE
[FEAT] Domain 객체 생성 및 DDL 테스트

### ISSUE THREAD

**Issue by honeySleepr** [juni8453/spring-cafe-jpa#7]
## 💡 issue
Member, Article 도메인을 생성하고, JPA를 통해 DDL이 제대로 작동하는지 확인합니다

## 📝 todo
- [x] Member, Article 클래스 생성
- [x] JPA를 사용하여 단방향 매핑
- [x] MySQL 워크벤치를 통해 테이블 생성 확인
